export const ANIMA_EFFECTS: {
  [exaltType: string]: {
    [caste: string]: {
      description?: string;
      Passive?: string;
      Active?: string;
      Iconic?: string;
    };
  };
} = {
  
Lunar: {
  "Full Moon": {
	description: "The Full Moon is a warrior to their core, meeting the world’s dangers head on through physical prowess and dogged determination. They might be a warrior king or gloried hero. Their animal form is powerful and strong, such as a bear, bull, or horse. Their caste mark is a silver disc, and their anima shines bright and steady as the full moon. At the end of each session, Full Moon Castes gain an Exalt milestone if they defeated a significant foe in single combat.",
	Passive: "Unstoppable (Passive): Extras (p. 316) cannot deal damage to the Full Moon. Any damage rolls they would make on Step 7 generate 0 successes. Battle groups subtract the Full Moon’s Essence from their damage on Step 7.",
	Active: "Crushing Might (Active): The Lunar adds her Essence in automatic successes to any Force or Fortitude roll that is not an attack. This applies to Build Power actions and gambits as an exception.",
	Iconic: "Impossible Vigor (Iconic): The Lunar heals one damage any time they Incapacitate an enemy.",
  },
  "Changing Moon": {
    description: "The Changing Moon is a silver-tongued trickster, relying on cleverness and irrepressible charm to beat their foes. They might be a spy, assassin, or scout. Their animal shape is quick, clever, and often beautiful, such as a fox, cat, or raven. Their caste mark is a crescent moon, and their anima is a shifting of silver light and dark blue or purple shadows. At the end of each session, Changing Moon Castes gain an Exalt milestone if they committed a successful act of espionage or sabotage.",
    Passive: "Silver Tongue (Passive): Trivial targets cannot detect any lie the Changing Moon tells and accept it as truth no matter how outlandish. The Changing Moon cannot make them commit self-harm or do things they would not be capable of.",
    Active: "Trickster’s Cant (Active): The Lunar adds her Essence in automatic successes to social rolls made to persuade, bargain, or deceive. The Lunar must beguile their target in some regard.",
    Iconic: "Untouchable (Iconic): In combat, enemies targeting the Changing Moon with any action suffer a dice penalty equal to her Essence. Outside of combat, enemies cannot identify the character as anything other than some form of their iconic animal shape: either in a terrifying war-form or as a radiant god-beast. Onlookers still know she is some kind of magical being, if not a Lunar.",
  },
  "No Moon": {
    description: "The No Moon relies on intellect and wisdom. They like riddles and secrets, and challenge clever foes just to prove their superiority. They have a knack for sorcery. Their animal is one that symbolizes wisdom, mystery, or communion with mystical forces, such as an owl, snake, or octopus. Their caste mark is a silver circle, and dark blue and purple shadows cloud their anima, with just a trace of silver light at the edges. At the end of each session, No Moon Castes gain an Exalt milestone if they saved the day or changed the course of events with an application of wisdom, discretion, or their secret knowledge.",
    Passive: "Unseen Moon (Passive): Trivial targets cannot see or hear the No Moon unless the Lunar chooses to allow it. Significant characters suffer a three-dice penalty to determine her identity if she wishes to conceal it.",
    Active: "Silver Wisdom (Active): The Lunar adds their Essence in automatic successes to Fortitude or Finesse rolls involving observation, study, or the pursuit of knowledge, as well as Focus Will rolls.",
    Iconic: "Dark Moon’s Blessing (Iconic): All mundane efforts at stealth fail in the No Moon’s presence. Hidden objects fall from their hiding place. Creatures using Charms to hide must make a Stealth roll against a difficulty of 3 plus the No Moon’s Essence. Trivial targets keeping a secret from the No Moon immediately spill it, while non-trivial characters roll Integrity against a difficulty of her Essence or do the same.",
  },
  "Casteless": {
    description: "The Casteless may be newly Exalted, and not yet caught up with the Silver Pact. Or maybe they’re an elder Lunar who chooses to remain Casteless — either way they don’t benefit from moonsilver tattoos. They may have any kind of animal form. Their caste mark and anima are ever-changing, like the phases of the moon. At the end of each session, Casteless gain an Exalt milestone if they successfully executed a clever and daring plan.",
    Passive: "Reflected Moon (Passive): The Casteless chooses a passive anima effect from another Lunar caste to use as their own. They can change the passive effect whenever they gain a personal or Exalt milestone.",
    Active: "Shifting Moon’s Reserve (Active): Choose an Attribute + Ability roll iconic to the character. The Casteless always adds Essence in automatic successes to that roll. Choose the Attribute + Ability when this effect comes into play. It cannot be switched until the next scene.",
    Iconic: "Chimera’s Visage (Iconic): The Casteless may waive the usual cost for shapeshifting. While in iconic anima, the Casteless is immune to any effect that would transform her body against her will. She may spend 2 anima to end any single transformation already in effect when she reaches Iconic.",
  }
}
,
  
Solar: {
  "Dawn": {
    description: "The Dawn Caste comprises mighty warriors, charismatic generals, and genius strategists who fiercely defend their charges and lead armies to victory. Their animas are sunrise-hued: pale yellow, blue, and pink. Morning birds and hunting hawks call within, accompanied by the smell of molten metal. Their caste mark is a golden sunburst. At the end of each session, Dawn Castes gain an Exalt milestone if they fought in a battle, defended an ally, or intimidated an enemy into avoiding battle.",
    Passive: "Supernal Warrior (Passive): Without needing to roll, defeat up to the Dawn’s Essence in Extras (p. 316) on their turn, and add the Dawn’s Essence in dice to damage against battle groups (p. 322). Additionally, battle groups increase the difficulty to resist a rout check (p. 323) by the Exalt’s Essence.",
    Active: "Fearsome Visage (Active): The Dawn adds their Essence in automatic successes to attempts to frighten or intimidate an opponent, even if that opponent cannot normally be intimidated (such as mindless undead or automatons). Any gambits based on fear or intimidation have their cost reduced by one.",
    Iconic: "Unconquered (Iconic): At 10 anima, reflexively follow any Ranged or Close Combat attack with a secondary attack using a different Ability — including any rules or effects which allow Ability substitutions. These attacks must target different opponents unless the opponent is a single Size 3 or greater battle group or if they possess one of the following qualities: furious dragon’s ire, legendary size, or unstoppable (p. 317).",
  },
  "Zenith": {
    description: "The Zenith Caste are faithful priests and fiery orators, who inspire their followers to strive for justice. They’re holy warriors who vanquish the dead and creatures of darkness. Upon their Exaltation, the Unconquered Sun speaks directly to them. Their animas are the brilliant white and gold of the midday sky, streaked with cobalt. At the Iconic level, images of bulls, pillars, and other unyielding objects appear. Their caste mark is a golden solar disc. At the end of each session, Zenith Castes gain an Exalt milestone if they inspired a significant character with their words.",
    Passive: "All Eyes Upon Me (Passive): Trivial targets cannot ignore the Zenith’s social actions and will do as she asks as long as the request is reasonable. The Zenith gains the dice bonus from refusing her influence if any target chooses a hard bargain. Outside of combat, the Zenith may spend a mote to sanctify a corpse and reduce it to ash, rendering it beyond the reach of necromancy.",
    Active: "Purity of Purpose (Active): The Zenith adds their Essence in automatic successes to Presence and Performance rolls, or instantly reduces to fine ash any undead Extras or corpses they can perceive. Add the Zenith’s Essence in damage dice against undead battle groups.",
    Iconic: "Highest of Holies (Iconic): Add the Solar’s Essence in automatic successes to attacks against creatures of darkness. These attacks deal aggravated damage. The first time the Zenith reaches iconic anima in a scene, any battle group led by or consisting of creatures of darkness must immediately make a rout check with the difficulty increased by the Exalt’s Essence.",
  },
  "Twilight": {
    description: "Passionate in their pursuit of knowledge, the Twilight Caste are traveling scholars, engineers, and sorcerers, seeking to bring wisdom to the world and improve peoples’ lives. Their animas reflect the colors of sunset and early evening. At the Iconic level, images of tomes and gears swirl within. Their caste mark is a golden circle, filled with gold on the top and empty on the bottom half. At the end of each session, Twilight Castes gain an Exalt milestone if they used their knowledge to help a significant ally.",
    Passive: "Joyous Pursuit (Passive): Reduce difficulty to overcome obstacles while working on a venture (p. 151) involving investigation, research, or planning by the Twilight’s Essence, to a minimum of one.",
    Active:  "Indefatigable Genius (Active): Add the Solar’s Essence in automatic successes to Craft and Sagacity rolls, including Build Power and Focus Will actions.",
    Iconic: "Summoner’s Call (Iconic): Spend 5 anima. The Twilight may summon a minor elemental or First Circle demon of her choice, instantly calling it to her side. It remains bound to her for the rest of the scene, before sublimating into raw Essence or returning to Malfea, respectively.",
  },
  "Night": {
    description: "The Night Caste are spies and assassins, striking down the unrighteous from the cover of darkness. Where the other Lawgivers’ displays of power draw attention, Night Caste Solars are subtle. Shades of gray, violet, and black twist through their pale gold animas. At the Iconic level, they flash with the glint of moonlight on steel, and trail shadows in their wake. Their caste mark is an empty golden circle. At the end of each session, Night Castes gain an Exalt milestone if they successfully stole an important item or gained access to a locked or guarded space undetected.",
    Passive: "No One Special (Passive): The Night Caste can dampen her anima, preventing others from seeing it until she wants to be noticed. She cannot suppress her iconic anima. She gains a three-dice bonus to any roll to pretend to be someone she’s not.",
    Active: "Cloak of Shadows (Active): The Night Caste wraps her anima around her like a cloak and moves about unseen. Add her Essence in automatic successes to Stealth and Athletics rolls, including Build Power actions. Anyone who does notice her sees only a flickering shadow-visage; it’s impossible to discern her identity.",
    Iconic: "Vanishing Foe (Iconic): Spend 1 anima. After resolving a successful attack, the Night Caste may move instantly to any other location in the scene and gain her Essence in Power. Out of combat she becomes an immaterial thing and can move through solid matter as long as she ends her movement in an open space.",
  },
  "Eclipse": {
    description:"The Eclipse Caste are diplomats, negotiators, and peacemakers. They mend rifts between nations, de-escalate conflicts, and oversee bargains with the Fair Folk. Their white-and-gold animas coruscate outward into wispy trails like the corona of an eclipse. At the Iconic level, symbols of peace appear within them, while harmonious voices sing. Their caste mark is a golden disc within a circle. At the end of each session, Eclipse Castes gain an Exalt milestone if they successfully made a deal or defused a conflict between two significant characters or groups.",
    Passive: "Universal Scholar (Passive): The Eclipse may use an Exalt or minor milestone to learn qualities with the Eclipse keyword (p. 318) from spirits, Fair Folk, and other supernatural beings. For 2 anima, the Eclipse may seal an oath between two or more parties. They suffer a two-dice penalty to any subsequent rolls for the rest of the session if they break the agreement.",
    Active: "Esteemed Guest (Active): When the Eclipse negotiates with demons, Fair Folk, spirits, or the intelligent dead, they must welcome the Eclipse and entourage and present them with human hospitality. These beings must treat the Circle and her entourage with due respect for the duration of the scene. If the Eclipse or her guests act with hostility first, all subsequent hostile actions by the Eclipse and her allies (such as making attacks, threats, or Building Power, p. 183) are made at a difficulty increased by the Eclipse’s Essence.",
    Iconic: "Venerated Witness (Iconic): Everyone in the scene must honor their agreements with other characters in the Eclipse’s presence. If they choose not to, they suffer her Essence in increased difficulty to all actions taken to go back on their word. For 5 anima, the Eclipse may seal a greater oath between two parties. Anyone who chooses to break their vow suffers an appropriately grand curse determined by the Storyteller and player. The other party is aware of how and when the promise was broken.",
  }
}
,
  
"Dragon-Blooded": {
  Air: {
    description: "Air Aspects are idealists, visionaries, scholars, and innovators. They see the potential inherent in everyone and view the world as it could be. Their blue-and-white anima banners whirl and billow like storm clouds. At the Iconic level, lightning flashes, and birds and dragons glide within. At the end of each session, Air Aspects gain an Exalt milestone if they took an action toward furthering a long-term goal.",
    Passive: "Buoyed by the Wind (Passive): Once per turn, the Air Aspect may leap one additional range band vertically or horizontally as part of a movement action. She takes no falling damage from short range drops.",
    Active: "Mela’s Breath (Active): Subtract two dice from all ranged attacks targeting the Air Aspect.",
    Iconic: "Eye of the Hurricane (Iconic): Increase the Air Aspect’s Defense and the Defense of all allies within short range by half her Essence, rounded up. When targeted by influence which would sway her away from a long term goal or would drive her to act impulsively, increase her Resolve by one.",
  },
  Earth: {
    description: "Earth Aspects are implacable foes on the battlefield, standing firm to defend their allies. Stoic and resilient, they believe in strong foundations and sturdy structures, whether they’re building a community, an architectural marvel, or an imperial legion. What an Earth Aspect builds endures. Their yellow-and-white animas smell of loam and rumble like the shifting earth. At the Iconic level, mountains loom behind them and oxen and rocky dragons plod along in their glow. At the end of each session, Earth Aspects gain an Exalt milestone if they stood their ground against a foe.",
    Passive: "Fury of the Earth (Passive): The Earth Aspect reduces the cost of the knockback or knockdown gambits against extras to zero. Outside of combat, she may knock trivial characters within short range prone or one range band away without making an attack roll.",
    Active: "Pasiap Still Stands (Active): Add the Earth Aspect’s Essence to the cost of throw, knockback, and knockdown gambits used against them. This cannot make the cost exceed 10.",
    Iconic: "Unyielding Stone (Iconic): Add the Exalt’s Essence to her Soak for the remainder of the scene. The character cannot be targeted with the throw, knockback, and knockdown gambits. She may spend 2 anima when denying influence and prevent the target from gaining the dice bonus from her refusal. She may not apply this effect to the target again during the same scene.",
  },
  Water: {
    description: "Calm and relentless Water Aspects adapt to obstacles and wear down stubborn foes. As diplomats, investigators, and naval commanders, they see many paths to a satisfying solution. Their dark-blue and sea-green animas smell like brine and babble like brooks. At the iconic level, whirlpools churn within, and fish, siakas, and water dragons swim in their depths. At the end of each session, Water Aspects gain an Exalt milestone if they adapted their plans to accommodate a significant change of circumstances.",
    Passive: "Surface Skimmer (Passive): The Water Aspect may move along any liquid surface like it was solid ground — though this doesn’t afford her protection from acid or demon-tar — and breathes water as easily as air. She suffers no penalty to move or attack while underwater.",
    Active: "Flow of Daana’d (Active): Add Essence automatic successes to gambits where the Water Aspect attempts to disarm an opponent or pilfer an item. When an opponent targets her with a grapple or attempts to ensnare her, the Exalt adds her Essence to Defense.",
    Iconic: "Flow Like Water (Iconic): Once per turn, the Water Aspect may roll an attack twice on Step 3 and choose to keep the better result. In non-combat scenes, she may reroll any roll involving investigation, negotiation, or relentless pursuit.",
  },
  Fire: {
    description: "Passionate and dynamic, Fire Aspects’ emotions burn brightly. They sear their marks across the world as warriors, politicians, and iconoclasts. Their fiery red, orange, and gold animas smell of smoke or hot metal. At the Iconic level, volcanoes erupt within, and dragons and phoenixes cavort in the flames. At the end of each session, Fire Aspects gain an Exalt milestone if their passionate deeds or speeches influenced a significant character or group to take action.",
    Passive: "Where There’s Smoke (Passive): At the start of any scene, the Fire Aspect may sense anyone present in the scene who harbors grudges or heated emotions. Figuring out the cause of their enmity is up to the character. She gains a bonus die to any social actions to uncover or leverage those emotions.",
    Active: "Hesiesh’s Passion (Active): The Fire Aspect gains her Essence in automatic successes on social actions to inspire a crowd or persuade a target to act on his ambitions. She also becomes immune to mundane environmental hazards based on fire and heat for the scene and reduces the damage of magical sources or attacks by two dice (or 1 health level if it is not rolled).",
    Iconic: "Wildfire Dance (Iconic): The Fire Aspect’s fury ignites her weapons. The Exalt subtracts her Essence from the target’s Soak on Step 6. On a hit, the target catches fire and suffers from the burning surroundings hazard (p. 146) and increases the difficulty on the resistance roll by the Exalt’s Essence. The target rolls reflexively for this hazard at the end of the Exalt’s turn.",
  },
  Wood: {
    description: "Deeply attuned to the cycle of life and death, Wood Aspects are healers and poisoners, thrill seekers, and beast-tamers. New experiences exhilarate them. Vibrant greens color their animas, which smell of fresh-mown grass and blooming flowers. At the Iconic level riotous vines surround them, and forest animals and wood dragons stalk their branches. At the end of each session, Wood Aspects gain an Exalt milestone if they experienced something new and exciting to them with a significant character or group or their actions fostered change in a significant character or group.",
    Passive: "Natural Immunity (Passive): The Wood Aspect is immune to plant-based poisons and applies a two-success bonus on rolls to resist other poisons or disease.",
    Active: "Spring of Sextes Jylis (Active): Spend 1 anima on Step 2. Add the Exalt’s Essence to Defense against one attack.",
    Iconic: "Sap of Life (Iconic): Spend 1 Anima reflexively to heal one health level, either that the Wood Aspect’s taken or an ally within short range has suffered, starting with the most severe. She may spend up to 10 anima on this effect and may apply it to multiple targets.",
  }
},

Liminal: {
  Blood: {
    description: "The Child of Blood is born from desire, greed, and ambition. She is a great orator, painting a future where her audience has exactly what it always wanted. When she spends too much Essence, her skin takes on the pallor of the grave, her eyes become blood-red, and dark water drips from her body. At the end of each session, Blood Aspects gain an Exalt milestone if they persuaded someone to act on their greed for power, money, or carnal pleasure.",
    Passive: "Passion’s Heart (Passive): The Liminal senses if someone has a Virtue or Intimacy grounded in desire, greed, or ambition. If so, she may spend 1 mote to determine its exact nature.",
    Active: "Call for Blood (Active): The Liminal adds her Essence in automatic successes to Embassy, Performance, and Presence rolls when inciting desire, greed, or ambition.",
    Iconic: "Bloodlust (Iconic): The Liminal grant herself and all allies automatic successes to attack rolls equal to their targets’ wound penalty (even if the enemy has an effect that would suppress wound penalties). This effect persists for the rest of the scene, even if the Liminal is no longer at iconic anima.",
  },
  Breath: {
    description: "The Child of Breath is born from a moment of regret or repentance. He is a contemplative creature, always looking to the past or waiting for others to act first. Foul winds carrying the stench of open graves pick up when he spends too much Essence. His skin and lips take on a bluish tone, and his voice becomes a raspy whisper. At the end of each session, Breath Aspects gain an Exalt milestone if they punish the wicked or make them repent. The player determines what her character thinks is wicked.",
    Passive: "Depths of Regret (Passive): The Liminal senses if someone has a Virtue or Intimacy grounded in regret or repentance. If so, he may spend 1 mote to determine its exact nature.",
    Active: "Swift Retaliation (Active): Spend 1 anima. Make a counterattack on Step 8 and treat it as a distract gambit to insult, provoke, or rebuke the target. The Liminal gains his Essence in bonus successes on this attack.",
    Iconic: "Breath of Regret (Iconic): All enemies targeting the Liminal must make a reflexive Integrity roll on Step 1, difficulty 2 + his Essence, to strike him. If the enemy fails, they must attack someone else, at a dice penalty equal to the Liminal’s Essence.",
  },
  Flesh: {
    description: "The Child of Flesh is the product of rage and vengeance. They thrive on action and aggression and hate waiting. When they spend too much Essence, the stitches on their skin become more pronounced, the separate parts of their body barely held together while their wounds ooze black pus. At the end of each session, Flesh Aspects gain an Exalt milestone if they defeated a story-important foe in combat.",
    Passive: "Scent of Rage (Passive): The Liminal senses if someone has a Virtue or Intimacy grounded in rage or vengeance. If so, they may spend 1 mote to determine its exact nature.",
    Active: "Strike the Flesh (Active): The Liminal may subtract up to their Essence in dice from their decisive attack roll on Step 3 and add them as automatic successes on the damage roll during Step 7.",
    Iconic: "Weakness of Flesh (Iconic): The Liminal and any allies within short range inflict 1 extra automatic damage on Step 7 during decisive attacks. This rises to 2 extra damage when they reach Essence 5. This effect costs 1 anima per round the Liminal wishes to apply it. The Exalt may apply this effect for the rest of the scene, even if the Liminal is no longer in iconic anima.",
  },
  Marrow: {
    description: "The Child of Marrow is a creature of curiosity and obsession, born from those same passions. She likes to observe and analyze, ever prying at secrets. Her body becomes desiccated if she spends too much Essence, her teeth and nails seeming unnaturally long. At the end of each session, Marrow Aspects gain an Exalt milestone if they learned a story-important information or discovered a piece of lost knowledge.",
    Passive: "Shining Obsession (Passive): The Liminal senses if someone has a Virtue or Intimacy grounded in curiosity or obsession. If so, she may spend 1 mote to determine its exact nature.",
    Active: "Hidden Marrow (Active): The Liminal adds her Essence in automatic successes on Embassy, Sagacity, and Stealth rolls to ferret out secrets.",
    Iconic: "Marrow’s Riddle (Iconic): Spend 3 anima. As a simple action, the Liminal may present any one character in the scene with a riddle. The target must roll Sagacity at difficulty 2 plus the Liminal’s Essence or stand lost in thought for her Essence in rounds. Puzzling over the riddle may not be part of a flurry. This reverie breaks if someone attacks them.",
  },
  Soil: {
    description: "The Child of Soil rises from sorrow and yearning. He’s introspective, more interested in omens and the secrets of death than in human company. Grave dirt coats his skin when he spends too much Essence and worms writhe in his eyes and mouth. At the end of each session, Soil Aspects gain an Exalt milestone if they acted on an omen (see: Written in Soil) or other foresight and successfully avoided danger, created a positive outcome, or helped a significant character.",
    Passive: "Sorrow’s Call (Passive): The Liminal senses if someone has a Virtue or Intimacy grounded in sorrow or yearning. If so, he may spend 1 mote to determine its exact nature.",
    Active: "Written in Soil (Active): The Liminal may use an action to invoke an omen — a cryptic phrase of her own design that portends a future possibility. This adds the Liminal’s Essence in dice to the target’s next roll. She may use this on herself.",
    Iconic: "From Dust (Iconic): Once per scene, the Liminal and any allies within close range immediately heal two health levels when he enters iconic anima, starting with the most severe. He may spend 1 anima per ally to let them heal a third health level.",
  },
},

Infernal: {
  Azimuth: {
    description: "War is the Azimuths’ orienting principle. Intent on destroying Creation’s and heaven’s corrupt regimes, they lead demon armies to pull tyrants from their thrones. Chosen from among those who suffered from violence and the ravages of war, now they conquer, bent on revenge and protecting the weak…or destroying the mighty. Their animas ripple with the glinting tones of brass. Their caste marks are an unholy sunburst with eight rays, with the larger diagonal cross rays emphasizing a center without a circle. At the end of each session, Azimuth Castes gain an Exalt milestone if they led other characters in a bloody battle or their actions caused an outbreak of violence.",
    Passive: "Font of War (Passive): Without needing to roll, the Azimuth defeats her Essence in Extras (p. 316) on her turn and add the Exalt’s Essence in dice to damage against battle groups. Additionally, each time the Exalt damages a battle group, increase the difficulty to resist a rout check by 1, to a maximum of 5.",
    Active: "Terrifying Visage (Active): Add her Essence in automatic successes on social actions to intimidate or terrify a foe, even foes that cannot normally be intimidated. Any gambits based on fear or intimidation have their cost reduced by one.",
    Iconic: "Towering Demon Emperor (Iconic): The Azimuth may transform immediately into Devil-Body Incarnation without paying the cost. Add the Exalt’s Essence in successes to Close Combat or Physique rolls for the rest of the scene so long as she is in Corona of Fury.",
  },
  Ascendant: {
    description: "Ascendant Castes are charismatic priest kings and blasphemous missionaries, seeking to expose weaknesses in Creation’s laws and undermine its unjust hierarchies. Ascendants are chosen from those condemned as wicked or counted among the lowly and despised. They rise from those spurned by society and preach radical or blasphemous teachings, calling those around them to question their beliefs and traditions. Their animas are full of swirling turquoise greens and shimmering silvers, often with faint tones of cerulean. Their caste marks are an empty green circle with a smaller partial disc cresting over the upper right side. At the end of each session, Ascendant Castes gain an Exalt milestone if they caused a significant character or group to take extreme action or her own provocative actions caused a significant character to gain or change an Intimacy.",
    Passive: "Shake Off Your Chains (Passive): Trivial targets cannot ignore the Ascendant’s social actions, giving in to their rebellious or violent instincts at her behest.",
    Active: "Laws of Hell (Active): Rebuking any authority not of the Yozis, the Infernal encourages listeners to exact justice with their own hands. Add her Essence in successes on social influence rolls provoking characters to acts of rebellion or anarchy.",
    Iconic: "No Gods, No Masters (Iconic): Defying divine hegemony, the Ascendant desecrates the ground around her out to medium range. She creates an environmental hazard of blazing sands with a difficulty of Essence + 2 that deals 2 damage per round until her anima falls below 6. While iconic, her attacks deal aggravated damage to gods and others who belong to the Celestial Bureaucracy, like Sidereals and some elementals.",
  },
  Horizon: {
    description: "Horizon Castes are sorcerers, savants, and visionaries. Before their Exaltations, Horizon Castes were denied opportunities for education via slavery or poverty, denied the opportunity to chase their intellectual pursuits or else were persecuted for their research by oppressive societies. Now, their brilliant minds turn toward achieving the heights they’ve envisioned. Their animas show this driving fire as ocean-green and white flames. Their caste marks are an empty green ring on the bottom, with a closed horizontal line erupting upward into a starburst. At the end of each session, Horizon Castes gain an Exalt milestone if they used their knowledge to interfere with or thwart a significant character’s plans.",
    Passive: "Knowledge at All Costs (Passive): Reduce the base number of obstacles the Horizon must overcome on a venture (p. 151) involving investigation, research, or planning by one, to a minimum of one.",
    Active: "Principles of Hierarchy (Active): Add the Horizon’s Essence in automatic successes for Craft or Sagacity rolls, including Build Power and Focus Will actions.",
    Iconic: "Power and Control (Iconic): Spend 4 anima to disrupt the Essence flowing through a target. The target adds half the Horizon’s Essence (rounded up) to the mote cost on Charms for the duration of the combat. They must pay 1 mote for Charms with no cost. If they cannot afford the Charm, they cannot activate it. Additionally, the Horizon can steal Will with a withering attack instead of gaining Power.",
  },
  Nadir: {
    description: "Infernals of the Nadir Caste are criminals, iconoclasts, and anarchists. Chosen from those who were once imprisoned — whether jailed, enslaved, or beholden to a rigid family — now no cage can hold them as they pursue their revenge or liberate others. Bright streaks of blood red whirl through their sea green animas. Their caste mark is an empty green ring, with an equally empty sunburst at the lowest point. At the end of each session, Nadir Castes gain an Exalt milestone if they infiltrate a significant character’s protected space or undermine them on a social matter.",
    Passive: "Subtle Enemy (Passive): The Nadir can dampen her anima, preventing others from seeing it until she wants to be noticed. She cannot suppress her iconic anima. She gains a three-dice bonus to any rolls to conceal her identity.",
    Active: "Death’s Shadow (Active): The Nadir wraps her anima around herself, passing unseen among trivial targets. Add her Essence in automatic successes to Athletics and Stealth rolls against non-trivial characters, including Build Power actions. If she’s detected, her identity can’t be determined.",
    Iconic: "Hell’s Silent Wind (Iconic): A zone of absolute silence envelopes the Nadir. Enemies in close range can’t hear or call out to allies, preventing them from taking advantage of any inspire or rally Build Power actions (p. 140) that rely on sound. Before making an attack, she may spend 1 anima to gain 1 Power, to a maximum of 5 Power.",
  },
  Penumbra: {
    description: "Ambassadors, spies, and negotiators, Penumbras are chosen from among those who rejected lives of wealth and power after seeing the corruption at its heart — or those with status betrayed by their inner circle, returned for vengeance. Now, they sow acrimony and distrust among the elite, determined to tear down Creation’s broken systems. Their animas are majestic dark greens and imperial purples, with patches of purest black. Their caste mark is a viridian-white disk, limned with fiery emerald flares radiating outward. At the end of each session, Penumbra Castes gain an Exalt milestone if they caused a significant character or group to back out of or break an agreement, contract, oath, or deal.",
    Passive: "Fiend to All Nations (Passive): Like their Eclipse counterparts, the Penumbra may learn Eclipse-keyword Charms or qualities from spirits, Fair Folk, and other supernatural beings. Their oaths are made as an Eclipse’s and sealed by the power of the Yozis, with a similar punishment for oath-breakers (see p. 63).",
    Active: "Scheming Mastermind (Active): When the Penumbra negotiates with demons, Fair Folk, spirits, or the dead, they must treat her and her retinue with respect unless they act with hostility first, per Esteemed Guest (p.63). Once per scene, the Penumbra may spend 2 anima to reduce a target’s Resolve by 3 against a persuade action (p. 132) to convince them to violate an agreement or act against their best interests.",
    Iconic: "Oathbreaker (Iconic): Once per scene, the Penumbra instills a Minor Tie of distrust toward a character or concept in a number of people equal to her Essence. Additionally, she may commit two motes to temporarily lift the burden of a sealed oath from a target. The person may defy their oath until the Penumbra withdraws the committed motes.",
  },
},

Sidereal: {
  "Mercury": {
    description: "The Chosen of Mercury are wanderers, pilgrims, and explorers, always seeking the horizon. Their animas are saffron yellow, tinged with a sense of far-away places: dust of the road, sea spray, and thunderstorms. At the end of each session, the Chosen of Journeys gain an Exalt milestone if they solved a problem through a path of least resistance or guided others through unknown or dangerous territory.",
    Passive: "Auspicious Journey Insight (Passive): When meeting a character, the Sidereal may ask a question about their recent whereabouts, previous travel, or origins and get an honest, useful answer from the Storyteller. Additional questions cost one mote each.",
    Active: "Lesser Sign of Mercury (Active): The Sidereal and allies ignore the effects of difficult terrain and transform the Sidereal’s Essence in dice to automatic successes any time they would need to roll for movement-related actions, including rolls to prevent falling, resist forced movement, or similar effects.",
    Iconic: "Greater Sign of Mercury (Iconic): Spend 10 anima. The Sidereal can teleport herself and her Circle or up to her Essence plus four allies to a crossroads, major thoroughfare, city center, port, or trade hub closest to the character’s location, depositing them in a safe spot of the Storyteller’s choice.",
  },
  "Venus": {
    description: "The Chosen of Venus are lovers, poets, and romantics tasked with bringing people together according to heaven’s design. Their animas are deep cerulean, tinged with a sense of romance: rose petals, silk, and wine. At the end of each session, the Chosen of Serenity gain an Exalt milestone if they deescalate a dangerous or violent conflict or soothe the emotions of a significant character.",
    Passive: "Auspicious Serenity Insight (Passive): When meeting a character, the Sidereal can ask a question about the character’s romantic interests, personal vices, or fond wishes and get an honest, useful answer from the Storyteller. Additional questions cost one mote each.",
    Active: "Lesser Sign of Venus (Active): The Sidereal and her allies may transform her Essence in dice to automatic successes on Performance and Craft rolls based on joy, love, or attraction, including Build Power actions.",
    Iconic: "Greater Sign of Venus (Iconic): Spend 10 Anima. The Sidereal halts all combat within the scene. Participating characters, including other players’ characters, may not make attacks, purchase gambits, Build Power, or use military tactics and naval combat stratagems until the Sidereal has had a chance to either flee or speak.",
  },
  "Mars": {
    description: "The Chosen of Mars are warriors, strategists, and firebrands overseeing the ebb and flow of battle. Their animas are bold crimson, tinged with conflict: the snap of banners in the wind, singing blades, and blood on grass. At the end of each session, the Chosen of Battles gain an Exalt milestone if a significant combatant heeded their counsel or wisdom, or their advice or preparation turned the tides of a significant conflict or led to an acceptable loss.",
    Passive: "Auspicious Battle Insight (Passive): When meeting a character, the Sidereal can ask a question about the character’s combat prowess, military goals, or favored strategies and get an honest, useful answer from the Storyteller. Additional questions cost one mote each.",
    Active: "Lesser Sign of Mars (Active): The Sidereal and her allies may transform her Essence in dice to automatic successes on Presence and War rolls to rally troops, devise tactics, and implement strategies, including Build Power actions.",
    Iconic: "Greater Sign of Mars (Iconic): Spend 10 anima. The Sidereal distributes 10 Power to her allies, divided as she chooses. If this makes a character exceed 10 Power, the recipient may bank the excess Power as additional damage dice instead, which must be spent before the end of the scene. This does not count towards the dice cap.",
  },
  "Jupiter": {
    description: "The Chosen of Jupiter are occultists, sages, and secret brokers who work in the shadows to uncover forbidden truths. Their animas are dark green, tinged with a sense of the unspoken: shuffling papers, flickering candles, and long shadows. At the end of each session, the Chosen of Secrets gain an Exalt milestone if they interfered in someone else’s affairs or discovered a significant secret.",
    Passive: "Auspicious Secrets Insight (Passive): When meeting a character, the Sidereal can ask a question about the character’s criminal activities, greatest shame, or field of expertise and get an honest, useful answer from the Storyteller. Additional questions cost one mote each.",
    Active: "Lesser Sign of Jupiter (Active): The Sidereal and her allies may transform her Essence in dice to automatic successes on Awareness, Sagacity, and Stealth rolls to do research, unravel mysteries, conduct reconnaissance, or investigate the unknown.",
    Iconic: "Greater Sign of Jupiter (Iconic): Spend 10 anima. For the rest of the session, actions that attempt to detect, track, investigate, or read the Sidereal and her allies suffer a three-success penalty, and automatically botch if failed. Characters with an Essence equal to or lesser than the Sidereal are compelled to tell the truth, and any attempt they make to deceive the Sidereal or her allies also automatically fails.",
  },
  "Saturn": {
    description: "The Chosen of Saturn are healers, assassins, and bureaucratic advisors who serve as harbingers of death and change. Their animas are violet, tinged with a sense of sorrow: whispering voices, crow wings, and cracking frost. At the end of each session, the Chosen of Endings gain an Exalt milestone if they completed a venture, brought a long-standing problem to a decisive conclusion, or saw a violent conflict to its end.",
    Passive: "Auspicious Endings Insight (Passive): When meeting a character, the Sidereal can ask a question about the character’s fears, health, or political ambitions and get an honest, useful answer. Additional questions cost one mote each.",
    Active: "Lesser Sign of Saturn (Active): The Sidereal and her allies may transform her Essence in dice to automatic successes on Embassy and Awareness rolls to anticipate danger or assess hostile motivations or reach a peaceful conclusion.",
    Iconic: "Greater Sign of Saturn (Iconic): Spend 10 anima for the scene. The Sidereal and her allies gain +1 Overwhelming on withering attacks; on decisive attacks, Soak cannot reduce their successes below the Sidereal’s Essence. Enemies who take damage within short range of the Sidereal may not choose to take a dramatic injury. If a dying character is present in the scene with the Sidereal, she may grant them a peaceful death after appropriately dramatic parting words, sending them immediately into their next life.",
  }
},

Abyssal: {
  "Dusk": {
    description: "The vanguard of Death’s army, Dusk Castes are warriors dedicated to the singular beauty of slaughter in all its hideous forms. Their animas tend toward pitch black with hints of purple, gray, and blood red. At the end of each session, Dusk Castes gain an Exalt milestone if they engaged a significant foe in bloody combat.",
    Passive: "Death is Inevitable (Passive): Without needing to roll, the Dusk slays up to her Essence in trivial characters on their turn; against nontrivial targets, their decisive attacks that hit always inflict at least one level of damage.",
    Active: "Fear Made Flesh (Active): When the Dusk flurries influence actions meant to intimidate, demoralize, or otherwise frighten a foe, reduce the flurry penalty by two on each action. They can also intimidate otherwise-mindless targets, such as automata. This includes any antagonist with the mindless quality (p. 317).",
    Iconic: "Walking Apocalypse (Iconic): Once per turn, she may respond to an attack on Step 8, making a counterattack with any combat Ability. If successful, she gains her Essence in bonus successes to damage during Step 5 of her next attack against the target.",
  },
  "Midnight": {
    description: "Priests to the powers of the Underworld and beyond, the Midnight Caste build cults among the living and the dead, preaching the gospel of the void. Their anima banners show rich, dark blues and deepest blacks. At the end of each session, Midnight Castes gain an Exalt milestone if they intimidated or coerced a significant character or group.",
    Passive: "Void Prophet (Passive): Once per scene, the Midnight may automatically intuit a character’s greatest losses, disappointments, and sorrows, treating these pain points as a Minor Intimacy for influence. Additional uses cost 1 mote each.",
    Active: "Apocalyptic Voice (Active): The Abyssal gains her Essence in automatic successes on social influence to inspire feelings of fear, peace, despair, or acceptance.",
    Iconic: "Reveal the Faithless (Iconic): Spend 5 anima. Characters within the scene suffer a five-success penalty to deceive or hide from the Midnight and her entourage. Those caught lying are infected with a minor disease of the Midnight’s choice, even if normally immune.",
  },
  "Daybreak": {
    description: "Geniuses who pursue discovery at any cost, Daybreaks are surgeons, necromancers, explorers, and scholars of forbidden lore. Their anima banners are a stately gray shot through with purple and dark green. At the end of each session, Daybreak Castes gain an Exalt milestone if they used their knowledge to provoke conflict with or undermine a significant foe.",
    Passive: "Dark Inspiration (Passive): Once per session, the Daybreak may make a second roll on a Craft or Sagacity venture (p. 151) regardless of if she has already made an applicable roll in this scene or session.",
    Active: "Underworldly Lore (Active): Add the Daybreak’s Essence in automatic successes to Craft and Sagacity rolls, including Build Power and Focus Will actions.",
    Iconic: "Gruesome Epiphany (Iconic): When her anima reaches iconic, the Daybreak intuits, reveals, or causes a vital weakness (physical, mental, or emotional) for a character, object, or structure within long range. The Daybreak and her allies double 8s on all rolls to attack or otherwise leverage this vulnerability until the start of the Daybreak’s next turn in combat or to the next roll each of her allies make during a venture or social influence. She may spend 2 anima to allow this effect to persist for the rest of the scene.",
  },
  "Day": {
    description: "The Day Caste walks beneath the light of the sun to do death’s work when it is least expected. They are assassins, saboteurs, and spies in the land of the living. Their animas are ethereal grays and blacks, tinged with sickly greens. At the end of each session, Day Castes gain an Exalt milestone if they committed a significant sabotage or infiltration.",
    Passive: "Walking in Daylight (Passive): The Day Caste can dampen her anima, preventing others from seeing it until she wants to be noticed. She cannot suppress her iconic anima. Additionally, she gains a three-dice bonus to attempts to conceal her deathly nature.",
    Active: "Grim Caul (Active): The Abyssal gains her Essence in automatic successes on Athletics and Stealth rolls while her anima is active, including Build Power actions. It is impossible to determine her identity.",
    Iconic: "Living Shadow (Iconic): The Abyssal’s body becomes immaterial — nothing more than shadow and Essence. She is immune to being grappled or restrained and can move through solid matter as long as she ends her movement in an open space. When she uses this effect as part of an outmaneuver Build Power action (p. 138), gain her Essence in additional Power.",
  },
  "Moonshadow": {
    description: "Death’s courtiers and emissaries, Moonshadows are sent into the world to parley on behalf of the apocalypse. Their animas are translucent silver and black sheets, with a faint corona of pale purple and green. At the end of each session, Moonshadow Castes gain an Exalt milestone if they made a deal with a significant character or group or sowed discord between significant characters or groups.",
    Passive: "God of the Ashes (Passive): Like their Eclipse counterparts, the Moonshadow may learn Eclipse-keyword Charms or qualities from spirits, Fair Folk, and other supernatural beings, and seal pacts with the power of the Neverborn. They pay the same anima cost to seal oaths as Eclipses, which suffer the same penalties for violation (p. 63).",
    Active: "Speaker for the Dead (Active): While negotiating with spirits, raksha, or ghosts, the Moonshadow and her allies must be given safety and human or ghostly hospitality. This lasts as per Esteemed Guest (p. 63). Promises or deals made during these negotiations are sanctified; anyone who chooses to break them suffers immediate misfortune determined by the Storyteller based on the broken oath.",
    Iconic: "Gates of Death (Iconic): Spend 5 anima to open a portal to the Underworld within medium range. It leads either to a safe location over which the Moonshadow has authority (such as a manse or her Deathlord’s realm), or to an interesting location of the Storyteller’s choice. The portal stays open for the rest of the scene or until the Moonshadow wills it closed.",
  }
},

Alchemical: {
  "Adamant": {
    description: "The Adamant Caste is a teacher, artist, or muse. They prize precision, artistry, and above all, efficiency. They refract and refine the spiritual lives of others with calculated performances and inhuman discipline. At the end of each session, Adamant Castes gain an Exalt milestone if their spiritual guidance caused a significant character to gain an Intimacy or if it improved the life of others.",
    Passive: "Muse (Passive): The Adamant Caste serves as muse to any one non-Exalt. That person adds the Exalt’s Essence in dice to any roll to which the Adamant’s inspiration contributes. This immediately raises any Extras (p. 316) to non-trivial characters.",
    Active: "Be More Precise (Active): When an attack targeting the Adamant Caste misses, she may spend 1 anima on Step 4 to inflict a success penalty to the attacker’s next attack action equal to her Essence. She may do the same on social influence rolls that fail to meet her Resolve.",
    Iconic: "Guiding Hand (Iconic): Spend 2 anima. For the rest of the scene, the Adamant Caste’s allies within short range gain dice equal to her Essence on attack or social influence rolls so long as the Exalt is physically present and not incapacitated. These dice do not count towards the cap.",
  },
  "Jade": {
    description: "The Jade Caste is hardworking and down to earth. Outgoing and social, he finds himself a folk hero without trying. He thrives working or fighting alongside his community. At the end of each session, Jade Castes gain an Exalt milestone if sheer hard work overcame a significant obstacle or led to a victory.",
    Passive: "Friendly Face (Passive): The Jade Caste can befriend any trivial character without a roll. His new friend feels immediately inclined to do something for him, like share a plot-important secret or give him the keys to the jail. The player and Storyteller should agree on what sort of important little favor the new friend does.",
    Active: "Hard as Jade (Active): Spend 1 anima to add Essence to Soak on Step 6, until the start of your next turn.",
    Iconic: "Stalwart Rock (Iconic): The Alchemical and any allies within short range add half his Essence, rounded up, to Soak. So long as he is physically present and not Incapacitated (p. 144), Followers (p. 102) and trivial targets under his protection cannot be harmed. This costs 5 anima and lasts until the end of the scene.",
  },
  "Moonsilver": {
    description: "The Moonsilver Alchemical is the perfect spy, scout, and assassin. They’re agile, quick, and not seen unless they want to be. This Exalt protects their community from dangers no one saw coming. At the end of each session, Moonsilver Castes gain an Exalt milestone if they infiltrated a secure location or discovered a significant enemy secret.",
    Passive: "Ephemeral Moon (Passive): The Moonsilver Caste can sneak past trivial targets without a roll. Non-trivial characters who might catch them have to make an Integrity roll at difficulty 3 in order to remember what they saw.",
    Active: "Quicksilver (Active): The Moonsilver gains their Essence in automatic successes to ambush attacks or attacks from concealment (p. 139), and any attack actions they take when acting before an enemy.",
    Iconic: "Strike Twice (Iconic): The Moonsilver spends 6 anima to act again during the same round, whether that’s taking social actions, stealth, attacking, etc. She must spend the anima and declare this effect on her turn. This is a full new turn, in which she may take two more actions.",
  },
  "Orichalcum": {
    description: "The Orichalcum Caste is a natural leader and hero. She’s forceful and decisive, with a tendency to brashness and dogmatism. She unites her community to repel all outside threats. At the end of each session, Orichalcum Castes gain an Exalt milestone if they guided a group to success, whether on a venture, in battle, or in a social engagement.",
    Passive: "Radiant Gold (Passive): The Orichalcum can persuade a leaderless battle group (p. 322) into accepting her as their leader without a roll. She gains her Essence in automatic successes to attempts to persuade non-trivial targets to follow her lead.",
    Active: "Righteous Scorn (Active): Against enemies toward whom she holds a negative Intimacy, or who have harmed or threatened a member of her community, the Alchemical gains her Essence in automatic successes when she targets them with an attack or social action.",
    Iconic: "Golden Leader (Iconic): Mortal troops under the Orichalcum’s command gain elite Drill, and +1 Size for the rest of the scene. The Exalt adds her Essence in dice to rout checks. While in her presence, members of her community increase their Resolve by 1.",
  },
  "Soulsteel": {
    description: "The Soulsteel Caste brings justice. He hears tales of a despot or war criminal preying on his community and sets out to punish them. No matter the distance, no matter their defenses he finds them and makes an example of them. At the end of each session, Soulsteel Castes gain an Exalt milestone if they punished the wicked or assisted another character with vengeance or attaining a just outcome. The player decides what her character deems wicked or just.",
    Passive: "Dark Presence (Passive): The Soulsteel Caste can intimidate trivial targets (p. 316) without a roll. He gains his Essence in automatic successes to attempts to intimidate or frighten non-trivial targets.",
    Active: "Shroud of Fear (Active): Anyone who targets the Soulsteel with a Close Combat attack must make a reflexive Integrity roll against difficulty 3 on Step 1 before any other effects are rolled, or the attack fails and must target someone else.",
    Iconic: "Steel’s Rebuke (Iconic): The Alchemical reduces enemy Soak by half her Force, rounded up, on Step 7 when she targets them with an attack. As an Alchemical Exalt, you were created and chosen by Autochthon before the Divine Revolution, thousands of years ago. Sealed away by your creator in ancient times, you have been awakened for less than 10 years.",
  },
  "Starmetal": {
    description: "The Starmetal Caste is the quiet manipulator, the unseen power behind their community’s leader. They always act for the greater good but tend to think they know better than everyone else. At the end of each session, Starmetal Castes gain an Exalt milestone if they secretly guided a group’s leader to decisions or persuaded a significant character to do things her way.",
    Passive: "Silent Star (Passive): The Starmetal Caste can order trivial characters in a position of authority to relay her orders without a roll. This doesn’t work if the command works against the character’s interests.",
    Active: "Guiding Light (Active): The Alchemical adds their Essence in automatic successes to Embassy and Sagacity rolls, including Build Power actions.",
    Iconic: "When Stars Align (Iconic): The Starmetal adds half their Essence in successes, rounded up, to both attack and damage rolls for herself and her allies within short range, which lasts until the end of the scene. This does not count towards the cap.",
  }
},

Getimian: {
  "Spring": {
    description: "Spring Castes are warrior-poets and guardians whose prowess is a thing of elegance and beauty. In their Origins, they protected what was most important to them with martial prowess, cunning, and courage. At the end of each session, Spring Castes gain an Exalt milestone if they inspired a significant character or group with honeyed words or visions of their perfect world.",
    Passive: "Smiling Stranger Allure (Passive): The first time the Getimian meets a character, they immediately develop a positive impression of her, granting two bonus dice to relevant influence actions, and offer any reasonable hospitality. Non-trivial characters can roll Integrity against difficulty 5 to resist.",
    Active: "Bravery Blooms Wild (Active): Add her total Flowing motes in dice to resist effects that inspire fear. If the Getimian succeeds, she gains a one-success bonus on her next roll against the source.",
    Iconic: "Better World Proposition (Iconic): Name a mission or goal in which the Exalt believes wholeheartedly. Characters within medium range must either accept a positive Minor Intimacy toward that goal or take the following hard bargain (p.134): suffer a two-success penalty to all actions for the rest of the scene as they are wracked with visions of a perfect future. They may refuse as normal.",
  },
  "Summer": {
    description: "Summer Castes are conquerors, visionary prophets, and iconoclasts, driven by steely conviction. In their Origins, they changed the world through destruction: wars, rebellions, assassinations, and the breaking of old orders. At the end of each session, Summer Castes gain an Exalt milestone if they brought a significant character or group under their control or seized control over a dangerous or chaotic situation.",
    Passive: "Impossible Conquest Authority (Passive): Trivial characters cannot ignore or refuse the Getimian’s demands, and must either comply or cower. Non-trivial characters that accept a hard bargain must not interfere with the Exalt’s actions or leave the scene. This demand cannot be unacceptable influence (p. 134) and can be refused as normal.",
    Active: "Ambition Always Thrives (Active): Add her Flowing motes in dice to resist effects that would slow, paralyze, or restrain the Getimian, including grapples. If she succeeds, she gains a one-success bonus on her next roll against the source.",
    Iconic: "Charting the Future’s Course (Iconic): When the Getimian’s anima reaches Iconic, roll Attribute + Awareness. Once per turn for the remainder of the scene, she may spend one of these successes to pose a hypothetical question to the Storyteller and get an honest, useful answer. For example: How would the queen react if I refused? What would happen if I chose the left door? Anyone acting on this insight gains the Getimian’s Essence in automatic successes to their next applicable roll. Insight is limited to the immediate future; it cannot predict long-term consequences, nor can it guarantee the results of a future roll.",
  },
  "Autumn": {
    description: "Autumn Castes are inspirational war leaders, healers, and saviors of the meek. In their Origins, they led their dominions and oversaw their charges with wrath born of overwhelming compassion. At the end of each session, Autumn Castes gain an Exalt milestone if they made a significant personal sacrifice for the sake of others or persuaded a significant character to put others before themselves.",
    Passive: "Thousand Elixir Tears (Passive): Characters under the Getimian’s care gain her Still motes in bonus dice to resist or overcome poison and disease. Once per session, she may pay up to her Essence in motes to heal that many levels of damage from another character.",
    Active: "Love Never Turns (Active): Add her Still motes in dice to resist effects that corrupt positive feelings or force the Getimian to act against a positive Tie. If the Getimian succeeds, she gains a one-success bonus on her next roll against the source.",
    Iconic: "Devil-Queen Salvation (Iconic): For the rest of the scene, the Getimian may redirect any attack against a character to whom she has a positive Intimacy to herself regardless of distance. Declare this on Step 2. All effects declared by the attacker apply. Effects within short range that indiscriminately slay trivial targets under her protection require a difficulty 5 Integrity roll to succeed.",
  },
  "Winter": {
    description: "Winter Castes are magicians, demiurges, and power brokers, shaping both mystical forces and societies with their genius, skill in manipulation, and far-reaching plans. In their Origins, they forged a new order, whether scheming in palace intrigues or transforming the world with powerful sorceries. At the end of each session, Winter Castes gain an Exalt milestone if they created or enforced order upon a significant character or group.",
    Passive: "Orderly World Insight (Passive): When she first meets a character, the Getimian automatically gains a sense of their status and position in society. When applicable, nontrivial characters may roll Stealth at difficulty 5 to conceal membership in a clandestine organization.",
    Active: "Deception Withers Away (Active): Add the Getimian’s Still motes in dice to resist illusions and other magic that deliberately confuses or misleads. If the effect has a fixed difficulty, she decreases it by half that amount, rounding up. If the Getimian succeeds, she gains a one-success bonus on her next roll against the source.",
    Iconic: "Laws of a New Creation (Iconic): When the Getimian’s anima reaches iconic, it burns the world out to medium range. Within this domain, she establishes a taboo — something that must not and cannot be done in her presence. This must be a specific behavior: targets cannot wear red, sing work songs, or recite Immaculate prayers, for example. The Getimian cannot force characters to stop making attacks or social influence actions. Ignoring this requires a difficulty 7 Integrity roll. This ends if the character leaves the range of the effect.",
  },
}

};
